#! /bin/sh
### BEGIN INIT INFO
# Provides:          httpserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts a simple HTTP server
### END INIT INFO

PATH=/sbin:/bin

. /lib/lsb/init-functions

case "$1" in
  start)
	log_action_msg "Starting HTTP server"
	start-stop-daemon --start --background -x /vagrant/bin/httpServer.py	
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	log_action_msg "Stopping HTTP server"
	/usr/bin/killall httpServer.py
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
